Add 'process-max' option and add multithreading to "dummy-dump" chek

diff --git a/pgbackrest_auto b/pgbackrest_auto
--- a/pgbackrest_auto
+++ b/pgbackrest_auto
@@ -106,6 +106,9 @@ while getopts ":-:" optchar; do
         custom-options=* )
             CUSTOMOTIONS=${OPTARG#*=}
             ;;
+        process-max=* )
+            PROCESS_MAX=${OPTARG#*=}
+            ;;
     esac
 done
 
@@ -160,7 +163,7 @@ Usage: $0 --from=STANZANAME --to=DATA_DIRECTORY [ --datname=DATABASE [...] ] [ -
         by default, the PostgreSQL version will be determined from the pgbackrest info
 
 --dummy-dump
-        Verify that data can be read out. Check with pg_dump >> /dev/null
+        Verify that data can be read out. Check with pg_dump
 
 --checksums
         Check data checksums
@@ -189,6 +192,8 @@ Usage: $0 --from=STANZANAME --to=DATA_DIRECTORY [ --datname=DATABASE [...] ] [ -
         Example: "--option1=value --option2=value --option3=value"
         See all available options: https://pgbackrest.org/configuration.html
 
+--process-max=
+        Max processes to use for restore and validate (default 1).
 
 EXAMPLES:
 ( example stanza \"app-db\" , backup host \"localhost\" (default value) )
@@ -354,6 +359,10 @@ elif [[ -n $DATNAME ]]; then
     restore_type_msg="Partial PostgreSQL Restore"
 fi
 
+# process-max default
+if [[ -z $PROCESS_MAX  ]]; then
+    PROCESS_MAX=1
+fi
 
 function sigterm_handler(){
     info "Recieved QUIT|TERM|INT signal"
@@ -513,8 +522,8 @@ function pgbackrest_exec(){
     if [ -f "${detail_rst_log}" ]; then info "See detailed log in the file ${detail_rst_log}"; fi
     info "Restore from backup started. Type: $restore_type_msg"
     # execute pgbackrest
-    echo "pgbackrest --config=${pgbackrest_conf} --stanza=${FROM} --pg1-path=${TO} ${pgbackrest_opt} --delta restore --process-max=4 --log-level-console=error --log-level-file=detail --recovery-option=${recovery_opt} --tablespace-map-all=${TO}_remapped_tablespaces"
-    if bash -c "pgbackrest --config=${pgbackrest_conf} --stanza=${FROM} --pg1-path=${TO} ${pgbackrest_opt} --delta restore --process-max=4 --log-level-console=error --log-level-file=detail --recovery-option=${recovery_opt} --tablespace-map-all=${TO}_remapped_tablespaces"
+    echo "pgbackrest --config=${pgbackrest_conf} --stanza=${FROM} --pg1-path=${TO} ${pgbackrest_opt} --delta restore --process-max=${PROCESS_MAX} --log-level-console=error --log-level-file=detail --recovery-option=${recovery_opt} --tablespace-map-all=${TO}_remapped_tablespaces"
+    if bash -c "pgbackrest --config=${pgbackrest_conf} --stanza=${FROM} --pg1-path=${TO} ${pgbackrest_opt} --delta restore --process-max=${PROCESS_MAX} --log-level-console=error --log-level-file=detail --recovery-option=${recovery_opt} --tablespace-map-all=${TO}_remapped_tablespaces"
     then
         info "Restore from backup done"
         sed -i 's/Restore_from_backup=0/Restore_from_backup=1/g' "${status_file}"
@@ -563,13 +572,28 @@ function dummy_dump(){
         for db in $databases; do
             info "Start data validation for database $db"
             if pgisready 1> /dev/null; then
-                info "  starting pg_dump -p ${PGPORT} -h 127.0.0.1 -d $db >> /dev/null"
-                if ! "${PG_BIN_DIR}"/pg_dump -p "${PGPORT}" -h 127.0.0.1 -d "$db" >> /dev/null
-                then
-                    sed -i 's/Data_validation=1/Data_validation=0/g' "${status_file}"
-                    error "Data validation in the database $db - Failed"
+                if [[ "$PROCESS_MAX" == '1' ]]; then
+                    # single-threaded dump is slower, but requires less disk I/O due to redirection to /dev/null
+                    info "  starting pg_dump -p ${PGPORT} -h 127.0.0.1 -d $db >> /dev/null"
+                    if ! "${PG_BIN_DIR}"/pg_dump -p "${PGPORT}" -h 127.0.0.1 -d "$db" >> /dev/null
+                    then
+                        sed -i 's/Data_validation=1/Data_validation=0/g' "${status_file}"
+                        error "Data validation in the database $db - Failed"
+                    else
+                        info "Data validation in the database $db - Successful"
+                    fi
                 else
-                    info "Data validation in the database $db - Successful"
+                    # Parallel dump speeds up the process for large databases,
+                    # but requires writing data and more disk space for the dump.
+                    mkdir -p "${PGDATA}"/dump/
+                    info "  starting pg_dump -p ${PGPORT} -h 127.0.0.1 -d $db -F d -j ${PROCESS_MAX} -f ${PGDATA}/dump/$db"
+                    if ! "${PG_BIN_DIR}"/pg_dump -p "${PGPORT}" -h 127.0.0.1 -d "$db" -F d -j "${PROCESS_MAX}" -f "${PGDATA}"/dump/"$db"
+                    then
+                        sed -i 's/Data_validation=1/Data_validation=0/g' "${status_file}"
+                        error "Data validation in the database $db - Failed"
+                    else
+                        info "Data validation in the database $db - Successful"
+                    fi
                 fi
             fi
         done
